### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by j4k0xb** [SteakEnthusiast/SteakEnthusiast.github.io#1]
Hi! I'm currently working on a [tool](https://github.com/j4k0xb/webcrack) that also deobfuscates and surprisingly does many things in a similar way as in your blog,
although I just found it a few minutes ago. It's very well explained.
Btw how did you get the dark theme for astexplorer? 👀 

In [Removing-Dead-or-Unreachable-Code](https://steakenthusiast.github.io/2022/06/04/Deobfuscating-Javascript-via-AST-Removing-Dead-or-Unreachable-Code/#Babel-Implementation) I noticed a small thing worth mentioning.
Currently it removes the variable `a` (it would also remove `fn` afterwards but babel's reference tracking is a bit buggy), which changes the runtime behavior:

```js
const a = fn();
function fn() { window.called = true; }
```
So I suggest only doing it when variable declarators are uninitialized or initialized with a literal.

For [Converting-Bracket-Notation-Dot-Notation-for-Property-Accessors](https://steakenthusiast.github.io/2022/05/28/Deobfuscating-Javascript-via-AST-Manipulation-Converting-Bracket-Notation-Dot-Notation-for-Property-Accessors/), property names can be more than variable names, e.g. `obj.function` is valid.
I used the [isIdentifierName](https://github.com/j4k0xb/webcrack/blob/be76c8ca4f08a14b7c5b124ac41c8a2325a7d2e2/src/transforms/computedProperties.ts#L11) function from babel-helper-validator-identifier

For [String-Array Map Obfuscation](https://steakenthusiast.github.io/2022/05/22/Deobfuscating-Javascript-via-AST-Manipulation-Various-String-Concealing-Techniques/#Example-2-String-Array-Map-Obfuscation), you also have to make sure that all references to the array are read-only member expressions:
```js
var _0xcd45 = ["name"];
fn(_0xcd45); // could modify it
_0xcd45[0] = 'test'; // modifies it, _0xcd45[0] is a LVal and cant be replaced with "name" 
console.log(_0xcd45[0]);
```

That's how I did it (for objects, but same idea applies): https://github.com/j4k0xb/webcrack/blob/be76c8ca4f08a14b7c5b124ac41c8a2325a7d2e2/src/deobfuscator/objectLiterals.ts#L76-L93

**Comment by SteakEnthusiast** [comment]
Thank you for taking the time to read and review the blog posts! That's a fantastic tool you're working on too 🙂

Your first and second points would be great additions. I'll probably update the tutorials when I get some time.

The last point however I've intentionally decided to exclude. My original intention for the blog was to teach beginners the fundamentals of deobfuscation, so that they can explore and discover these nuances from experience! I don't think it'd be practical to discuss and solve all of the possible edge cases in the post, and I wouldn't want to overwhelm them with all the possible edge cases😛 

A non-exhaustive list of some examples that would need to be considered:

```js
var a = ["foo", "bar", "baz", "qux"];

a.pop();

a.__defineGetter__(0, () => "aaaaa");
console.log(a[0]);

(function func() {
  var a = (1, eval)("a[2] = 1");
})();
```

Also, here's the link for the AST explorer dark theme:
https://github.com/nerodesu017/astexplorer-dark-theme

**Comment by j4k0xb** [comment]
Fair point with not overwhelming 😅
I didnt mean supporting every edge case or more advanced obfuscators, but being careful because string arrays are so common in source code
